"use client"

import React, { useState, useCallback } from "react"
import {
  Background,
  ReactFlow,
  addEdge,
  ConnectionLineType,
  Panel,
  useNodesState,
  useEdgesState,
  Handle,
  Position,
} from "@xyflow/react"
import CourseQuickView from "../Courses/CourseQuickView"

const edgeType = "smoothstep"

import "@xyflow/react/dist/style.css"

import COURSE_LIST from "../../data/autogenerated_course_info.json"

const getCourseData = (courseId) => {
  if (!courseId) return {}
  return COURSE_LIST.courses.filter(({ id }) => id === courseId)[0]
}

const ClickableNode = ({ data, selected }) => {
  const [clicked, setClicked] = useState(false)

  return (
    <div
      onClick={() => setClicked(!clicked)} // toggle color on click
      style={{
        padding: "10px",
        width: "150px",
        borderRadius: 8,
        border: "1px solid #222",
        fontSize: "15px",
        textAlign: "center",
        color: selected ? "white" : "black",
        background: selected ? "#feb61b" : "white", // 👈 color changes
        cursor: "pointer",
        transition: "background 0.2s ease",
      }}
    >
      <div>{data.label}</div>

      {/* Handles */}

      {!data.nodeType && (
        <>
          <Handle type="target" position={Position.Top} />
          <Handle type="source" position={Position.Bottom} />
        </>
      )}
      {data.nodeType === "input" && (
        <>
          <Handle type="source" position={Position.Bottom} />
        </>
      )}
      {data.nodeType === "output" && (
        <>
          <Handle type="target" position={Position.Top} />
        </>
      )}
    </div>
  )
}

const nodes = [
  {
    id: "401",
    courseId: "CMP0401",
    type: "clickable",
    data: { label: "CMP 401", nodeType: "input" },
    position: { x: -400, y: 0 },
  },
  {
    id: "445",
    courseId: "CS0445",
    type: "clickable",
    data: { label: "CS 445" },
    position: { x: -400, y: 100 },
  },
  {
    id: "447",
    courseId: "CS0447",
    type: "clickable",
    data: { label: "CS 447" },
    position: { x: -600, y: 200 },
  },
  {
    id: "449",
    courseId: "CS0449",
    type: "clickable",
    data: { label: "CS 449", nodeType: "output" },
    position: { x: -600, y: 300 },
  },
  {
    id: "1501",
    courseId: "CS1501",
    type: "clickable",
    data: { label: "CS 1501", nodeType: "output" },
    position: { x: -400, y: 250 },
  },
  {
    id: "1502",
    courseId: "CS1502",
    type: "clickable",
    data: { label: "CS 1502", nodeType: "output" },
    position: { x: -200, y: 300 },
  },
  {
    id: "1503",
    courseId: "CS1503",
    type: "clickable",
    data: { label: "CS 1503", nodeType: "output" },
    position: { x: -50, y: 200 },
  },
  {
    id: "441",
    courseId: "CS0441",
    type: "clickable",
    data: { label: "CS 441", nodeType: "input" },
    position: { x: -200, y: 100 },
  },
]

export const edges = [
  { id: "e12", source: "401", target: "445", type: edgeType, animated: false },
  { id: "e13", source: "445", target: "447", type: edgeType, animated: true },
  {
    id: "e22a",
    source: "445",
    target: "1501",
    type: edgeType,
    animated: false,
  },
  { id: "e22b", source: "447", target: "449", type: edgeType, animated: true },
  {
    id: "e22c",
    source: "445",
    target: "1502",
    type: edgeType,
    animated: false,
  },
  {
    id: "e2c2d",
    source: "441",
    target: "1503",
    type: edgeType,
    animated: false,
  },
  {
    id: "e2c2c",
    source: "441",
    target: "1502",
    type: edgeType,
    animated: false,
  },
]

const nodeWidth = 172
const nodeHeight = 36

const CourseGraph = () => {
  const [currentCourse, setCurrentCourse] = useState("")
  const [selectedNodeIds, setSelectedNodeIds] = useState([])

  const onSelectionChange = useCallback(({ nodes }) => {
    setSelectedNodeIds(nodes.map((n) => n.id))
  }, [])

  return (
    <div className="lg:flex h-[500px]">
      <div
        className="w-full h-[500px] nowheel"
        onWheel={(e) => {
          // Let the page scroll normally
          e.stopPropagation = () => {} // No-op to prevent React Flow stopping the scroll
        }}
      >
        <ReactFlow
          nodes={nodes}
          edges={edges}
          connectionLineType={ConnectionLineType.SmoothStep}
          proOptions={{ hideAttribution: true }}
          nodeTypes={{ clickable: ClickableNode }}
          fitView
          panOnScroll={false}
          zoomOnScroll={false}
          zoomOnPinch={false}
          panOnDrag={false}
          zoomOnDoubleClick={false}
          onSelectionChange={onSelectionChange}
          minZoom={1}
          maxZoom={1}
          onNodeClick={(e, node) => {
            setCurrentCourse(node.courseId)
            console.log(currentCourse)
          }}
          onWheelCapture={(e) => {
            // Allow normal page scrolling by letting the wheel event bubble
            e.stopPropagation = () => {} // noop: override ReactFlow’s event capture
          }}
        ></ReactFlow>
      </div>

      <div className="mb-5 border p-6 flex flex-col rounded br-8 lg:absolute lg:rounded-r-none lg:right-0 lg:w-1/4 shadow-md lg:border-r-0">
        <CourseQuickView {...getCourseData(currentCourse)}>
          <h3>Click a course on the graph to see details</h3>
          <p>
            The diagram <span className="md:hidden">above</span> shows the
            relationships between the core classes!
          </p>
        </CourseQuickView>
      </div>
    </div>
  )
}

export default CourseGraph
